### ISSUE TITLE
Training and testing on single dGPU

### ISSUE THREAD

**Issue by bashimr** [whwu95/Text4Vis#1]
Hi Guys

Looks like a great project.  Nice work. I am trying to explore it for zero-shot. I have an NVIDIA GeForce RTX 3080 on my machine. The instructions are to run the training on single machine with 8 GPUs. Is it possible/worthwhile to train and test the model on my machine? If so, any pointers to do that will be much appreciated.

Thanks. 

Imran

**Comment by whwu95** [comment]
Thank you for your interest in our work. 
You can perform zero-shot evaluation for a single card by simply changing --nproc_per_node=8 to --nproc_per_node=1. 
But I think it might be difficult to train video models with a single card.

**Comment by bashimr** [comment]
Thank you @whwu95.
