### ISSUE TITLE
Model zoo links expired

### ISSUE THREAD

**Issue by hoonga** [whwu95/Text4Vis#10]
Thanks for providing great resource for video recognitions.

It looks like one drive links have expired, and no longer able to download models from the model zoo.

**Comment by TJQdoIt9527** [comment]
> Thanks for providing great resource for video recognitions.
> 
> It looks like one drive links have expired, and no longer able to download models from the model zoo.

Hello, have you obtained the checkpoint in one drive? The current link still cannot be accessed.
Looking forward to your reply. Thank you very much

**Comment by whwu95** [comment]
I have extended the OneDrive expiration date. Please try downloading again.
