### ISSUE TITLE
Access to checkpoints

### ISSUE THREAD

**Issue by tomchen-ctj** [whwu95/Text4Vis#13]
Hi Wenhao,
Thanks for your great work!

I was trying to download the ViT/L-14-f8 checkpoint, but I encountered the following message: _"We're sorry, but ****@gmail.com can't be found in the unisyd-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you."_

Do you have any idea on how to solve this? 
Thanks!

**Comment by whwu95** [comment]
Please try downloading again.

**Comment by tomchen-ctj** [comment]
Hi @whwu95 ,
I've tried but still did not work. I also tried different accounts and different Internet environments.
Is there access for external users?

**Comment by whwu95** [comment]
It's so strange, I can open this link: https://unisyd-my.sharepoint.com/:u:/r/personal/wenhao_wu_sydney_edu_au/Documents/AAAI23-Text4Vis/k400-vitl-14-f8.pt?csf=1&web=1&e=mdOEns

**Comment by tomchen-ctj** [comment]
Maybe it's because you're the owner? 
Can you try using different accounts if possible? 

Thanks!

**Comment by whwu95** [comment]
Please refer the links in my new README.md. I think it works.

**Comment by tomchen-ctj** [comment]
Yayy!
Huge thanks! Now I'm closing the issue.
