### ISSUE TITLE
Could you provide the code/setting/threshold for producing Figure 1?

### ISSUE THREAD

**Issue by pha123661** [whwu95/Text4Vis#16]
Thanks for your great work in shedding new light on the transfer of VL models!

Could you please provide your code for plotting Figure 1? as I would like to test this idea on different tasks/datasets.

Or maybe you can share your experience with plotting, e.g., choosing which set of classes to plot, deciding on the right threshold, etc.

Thanks again!

**Comment by whwu95** [comment]
I use the heatmap function of the “seaborn” package to draw the figure, you can refer to its documentation.
