### ISSUE TITLE
Model zoo links expired

### ISSUE THREAD

**Issue by xushaowu** [whwu95/Text4Vis#22]
While the links to GITHUB are available, all links to OneDrive are expired. But the training of HDMB51, UCF101 involves pre-trained ViT-L models, which are unavailable to access. Please extend the OneDrive expiration date. Thx!

**Comment by whwu95** [comment]
I have extended the OneDrive expiration date. Please try downloading again.

**Comment by xushaowu** [comment]
> I have extended the OneDrive expiration date. Please try downloading again.

Thank you！
