### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by bashimr** [whwu95/Text4Vis#3]
@whwu95 

Are there any pre-trained models publicly available that I can use to test zero-shot?  If not, are you open to sharing the models trained on Kinetics400 for testing purpose?

Thanks,

Imran

**Comment by whwu95** [comment]
Hello,

Thank you for your interest in our project and for raising this issue. We have already open-sourced our pre-trained model, which can be found in the Model Zoo Section of our Readme. Specifically, we used the pre-trained ViT-L model with 8 frames for the zero-shot evaluation on UCF, HMDB, ActivityNet, and Kinetics-600.

**Comment by bashimr** [comment]
@whwu95 Thank you for getting back to me. I am looking for some assistance to try out the model for an internal project. Would you be open to a paid consulting via video conferencing?  Thanks.
