### ISSUE TITLE
Zero-shot Video Performance.

### ISSUE THREAD

**Issue by XiaoBuL** [whwu95/Text4Vis#4]
Hello, 

Thanks for your job! 

I've used the Kinetics-400 pre-trained model (ViT-L/14 with 8 frames downloaded from https://drive.google.com/file/d/1tGfE6HDjTGZ7-y6XM7D6UJAx1Esj-q7u/view?usp=share_link) to perform a cross-dataset zero-shot evaluation on **UCF-101 dataset**. And I get the following results:

  -----Full-classes Evaluation------
  Overall Top1 57.928% Top5 88.071%
  -----Half-classes Evaluation-----
  Top1: mean 69.553%, std 6.283%
  Top5: mean 92.737%, std 1.957%

  And in your paper, the performance of zero-shot video recognition is that: 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/36319750/223046641-398b61c0-a4ca-4d01-b81f-849599c52a36.png">

It's different and far below the performance that your paper reports. And I want to know which model is used for zero-shot video recognition. 

Thanks,

MS

**Comment by whwu95** [comment]
Hi,
Thank you so much for your interest in our work！

I have re-run the zero-shot evaluation using the following command: 
`sh scripts/run_test_zeroshot.sh configs/ucf101/ucf_zero_shot.yaml k400-vitl-14-f8`. 
The results are consistent with the paper.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/25218867/223298391-0ea6f5e2-c639-4424-b9cb-e1081e2677f5.png">

And I have uploaded the test logs for your reference.
[ucf_zeroshot.log](https://github.com/whwu95/Text4Vis/files/10904426/ucf_zeroshot.log)

Please let me know if you have any questions or comments. I'm happy to help in any way I can.

Wenhao

**Comment by XiaoBuL** [comment]
Hi.

Hi,

Hi, 
Thanks for your reply! 

I've found that I didn't load the pretrained model and get the expected results. 

Now it's OK! 

MS
