### ISSUE TITLE
Activitynet dataset

### ISSUE THREAD

**Issue by wangyangchen** [whwu95/Text4Vis#8]
Could you tell me how to extracts keyframes the Activitynet dataset and what are the rules?

**Comment by whwu95** [comment]
Hi,
Thank you for your interest in our work.
To extract keyframes from the ActivityNet dataset, we directly use ffmpeg and extract frames at a frame rate of 1 frame per second (FPS).

**Comment by wangyangchen** [comment]
Thanks for your reply!
