### ISSUE TITLE
About the dataloader.

### ISSUE THREAD

**Issue by ZMHH-H** [whwu95/Text4Vis#9]
Hi, thanks for your great job! I notice that there are two ways to load the video data: 1.extrated frames 2. on-the-fly decoding
Could you please provide some details about the difference in their loading speed? And how much memory space will the extracted frames take up (e.g. K400)?

**Comment by whwu95** [comment]
Hi, Minghao,

Thank you for your interest in our work.
I haven't specifically tested the speed of the two loaders, "extracted frames" and "on-the-fly decoding," in this context. In fact, all models discussed in this paper were trained using extracted frames. However, if you are using a solid-state drive (SSD), the speed difference between the two loaders may not be significant. If you choose to use extracted frames for training, it would require approximately 1 T of disk space for the K400 dataset.

**Comment by ZMHH-H** [comment]
Thank you for your reply, your advice is helpful to me!
